remote_theme: CaptainIRS/hacker-plus-theme

title: Ak4sh
author: Akash Kumar
description: Just Testing
disqus_forum_shortname: disqus_Fg6n6gkUmf
google_site_verification_content: # The 'content' tag for site verification
google_analytics: # Your Google Analytics Tracking ID

# Usernames and badges
htb_badge_no: 1243635 
thm_badge_no: 986648 
show_thm_htb_badges_in_nav: true
github_username: 
gitlab:
medium:
stackoverflow:
hacker_news:
linkedin: 0x1ak4sh
twitch: 
youtube:
twitter: 0x1ak4sh
facebook:
instagram: 0x1ak4sh
reddit:
pinterest:
telegram: Ak4sh0x1
steam:

# -------DO NOT ALTER -------#
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
exclude: [
   /*/*/_problems/*,
   scripts
]
plugins:
   - jekyll-seo-tag
   - jemoji
   - jekyll-sitemap
   - jekyll-github-metadata
collections:
   pages:
      output: true
      permalink: /:name
   writeups:
      output: true
   solutions:
      output: true
   blog:
      output: true
